version: '3.5'

services:
  nginx:
    image: nginx:1.15-alpine
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:localhost

  traefik:
    image: traefik:1.7
    command: -c /dev/null
      - "--api"
      - "--docker"
      - "--defaultentrypoints=https,http"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS:/certs/localhost/localhost.crt,/certs/localhost/localhost.key"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/.docker/traefik/certs/localhost:/certs/localhost

