version: '3.3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/localhost/localhost.crt,/certs/localhost/localhost.key" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"

    ports:
      - "8080:8080" # The Web UI (enabled by --api)
      - "443:443" # The HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./certs:/certs
  
  nginx:
    image: nginx:latest
    labels: 
      - "traefik.frontend.rule=Host:nginx.dev"
      - "traefik.backend=nginx"
